# Generated by Django 3.2.10 on 2021-12-30 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_usermaster_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('Mid', models.IntegerField(primary_key=True, serialize=False)),
                ('MenuType', models.CharField(max_length=100, null=True)),
                ('PMname', models.CharField(max_length=100)),
                ('DisplayOrder', models.CharField(max_length=100, null=True)),
                ('IsMobile', models.BooleanField(default=False)),
                ('IconImage', models.ImageField(upload_to='MenuImages')),
            ],
        ),
        migrations.CreateModel(
            name='SubMenu',
            fields=[
                ('SMid', models.IntegerField(primary_key=True, serialize=False)),
                ('Sname', models.CharField(max_length=100)),
                ('DisplayOrder', models.CharField(max_length=100, null=True)),
                ('IsMobile', models.BooleanField(default=False)),
                ('IconImage', models.ImageField(upload_to='SubMenuImages')),
                ('menumaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.menumaster')),
            ],
        ),
    ]
