# Generated by Django 3.2.10 on 2022-01-03 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='pageLink',
            field=models.CharField(choices=[('Bill Wise Sales Report', 'Bill Wise Sales Report'), ('Bill Wise Sales Report Detailed', 'Bill Wise Sales Report Detailed'), ('Bill Wise Sales Report old', 'Bill Wise Sales Report old')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submenu',
            name='pagelinktype',
            field=models.CharField(choices=[('Report', 'Report'), ('static', 'static'), ('Master', 'Master'), ('Document', 'Document'), ('DReport', 'DReport'), ('Calendar', 'Calendar'), ('MasterCalendar', 'MasterCalender')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
