# Generated by Django 3.2.10 on 2022-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_dmf_dmffield'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('Bill_Date', models.DateField()),
                ('Invoice_No', models.CharField(max_length=50)),
                ('Tally_MasterID', models.CharField(blank=True, max_length=15, null=True)),
                ('Total_Inventory_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=2, null=True)),
                ('Total_GST', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SGST_AMOUNT', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
