# Generated by Django 3.2.10 on 2022-08-17 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Region_Name', models.CharField(max_length=50, verbose_name='Region Name')),
            ],
        ),
        migrations.CreateModel(
            name='StateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State_Name', models.CharField(max_length=50, verbose_name='State Name')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.region')),
            ],
        ),
        migrations.CreateModel(
            name='CityMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('City_Name', models.CharField(max_length=50, verbose_name='City Name')),
                ('State', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.statemaster')),
            ],
        ),
    ]
