# Generated by Django 3.2.10 on 2022-08-17 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_rename_region_statemaster_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Region',
            new_name='RegionMaster',
        ),
    ]
