# Generated by Django 3.2.10 on 2022-05-13 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_hier2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hier3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hier3_name', models.CharField(max_length=50)),
                ('hier2', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='core.hier2')),
                ('hierarchy1', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='core.hier1')),
            ],
        ),
    ]
