# Generated by Django 3.2.10 on 2022-05-13 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gst_field.modelfields
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_hier5'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Item_Name', models.CharField(max_length=100)),
                ('Item_Code', models.CharField(max_length=30)),
                ('Batch_Enabled', models.CharField(blank=True, max_length=20, null=True)),
                ('UOM', models.CharField(max_length=10)),
                ('Principal_Company', models.CharField(max_length=100)),
                ('MRP', models.PositiveBigIntegerField(blank=True, null=True)),
                ('HSN_Code', models.CharField(blank=True, max_length=5, null=True)),
                ('GST_Rate', models.FloatField(blank=True, null=True)),
                ('GST_Applicable_From', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer_Code', models.PositiveIntegerField()),
                ('Customer_Group', models.CharField(blank=True, max_length=50, null=True)),
                ('City', models.CharField(blank=True, max_length=50, null=True)),
                ('Pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('Contact_person_name', models.CharField(blank=True, max_length=50, null=True)),
                ('GSTIN', gst_field.modelfields.GSTField(max_length=15)),
                ('ZIN_NO', models.CharField(blank=True, max_length=50, null=True)),
                ('Customer_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('State', models.CharField(blank=True, max_length=50, null=True)),
                ('Address', models.TextField(blank=True, max_length=250, null=True)),
                ('Contact_Number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('Email_ID', models.EmailField(blank=True, max_length=254, null=True)),
                ('PAN', gst_field.modelfields.PANField(max_length=10)),
                ('Customer_For_Code', models.CharField(choices=[('200253', '200253'), ('200326', '200326'), ('200385', '200385'), ('200625', '200625'), ('201184', '201184'), ('201494', '201494'), ('265848', '265848'), ('266684', '266684'), ('264104', '264104'), ('264101', '264101')], max_length=10)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
