# Generated by Django 3.2.10 on 2022-05-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20220513_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('InActive', 'InActive')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distributor_Name', models.CharField(max_length=100, unique=True)),
                ('Distributor_Code', models.CharField(max_length=25)),
                ('Distributor_For_Code', models.CharField(max_length=30)),
                ('Region', models.CharField(blank=True, max_length=25, null=True)),
                ('State', models.CharField(blank=True, max_length=30, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.TextField(blank=True, max_length=500, null=True)),
                ('PinCode', models.PositiveIntegerField(blank=True, max_length=6, null=True)),
                ('Contact_Person_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Contact_Number', models.PositiveIntegerField(blank=True, max_length=50, null=True)),
                ('Email_ID', models.EmailField(blank=True, max_length=100, null=True)),
                ('GSTIN', models.CharField(blank=True, max_length=25, null=True)),
                ('DL_NO', models.CharField(blank=True, max_length=100, null=True)),
                ('DL_NO_Valid_UPTO', models.DateTimeField(blank=True, null=True)),
                ('PAN', models.CharField(max_length=15, null=True)),
                ('TM_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('RIS_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('PS_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('PSM_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('ASM_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('RSM_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('BM_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('SH_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('BDM_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('HO_Email', models.EmailField(blank=True, max_length=200, null=True)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
        ),
    ]
