# Generated by Django 3.2.10 on 2022-05-13 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_distributor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='distributor',
            field=models.ForeignKey(default=1,on_delete=django.db.models.deletion.CASCADE, to='core.distributor'),
            preserve_default=False,
        ),
    ]
