# Generated by Django 3.2.10 on 2022-05-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_distributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bill_Date', models.DateField()),
                ('Invoice_No', models.CharField(max_length=50)),
                ('Tally_MasterID', models.CharField(blank=True, max_length=15, null=True)),
                ('Total_GST', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('SGST_AMOUNT', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('CGST_AMOUNT', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('IGST_AMOUNT', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Cash_Discount_Amount', models.DecimalField(blank=True, decimal_places=20, max_digits=20, null=True)),
                ('R_O_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Total_Invoice_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Customer_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customer')),
                ('Distributor_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='DetailSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sales_Quantity', models.PositiveIntegerField()),
                ('Sales_Rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Sales_Serial_No', models.CharField(max_length=50)),
                ('Sales_Batch', models.CharField(blank=True, max_length=30, null=True)),
                ('Sales_Discount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('Total_Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('Reference_No', models.CharField(blank=True, max_length=50, null=True)),
                ('Sales_Item_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
        ),
    ]
