# Generated by Django 3.2.10 on 2022-01-08 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMaster',
            new_name='Books',
        ),
    ]
