# Generated by Django 3.2.10 on 2022-05-13 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gst_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0003_rename_books_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gstin', gst_field.modelfields.GSTField(max_length=15)),
                ('pan', gst_field.modelfields.PANField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
