# Generated by Django 3.2.10 on 2022-06-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_delivery_note_delivery_note_details_detailofpurchase_detailsofpurchasereturn_opening_balance_purchas'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentMasterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.sales')),
                ('salesreturn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.salesreturn')),
            ],
        ),
    ]
