# Generated by Django 3.2.10 on 2022-06-13 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_documentmastertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmastertype',
            name='name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
